import os
import pandas as pd
from fuzzywuzzy import fuzz


# This python code finds the match (intersection) between two list.

# It supports fuzzy match, to handle misspelling or typing errors. The result includes the Levenshtein distance between the two strings under comparison (100 is perfect match)

# Example searching for::

#     ['Cambrxidge Collxdege', 'Canada College', 'Chaboet College', 'Chemmeketa Comunity Collage']

# gives::

#     Exact Match: ['Canada College']
#     Fuzzy Match [(92, 'Cambridge College'), (100, 'Canada College'), (97, 'Chabot College'), (93, 'Chemeketa Community College')]


a_list = ['Cambrxidge Collxdege', 'Canada College', 'Chaboet College', 'Chemmeketa Comunity Collage']

b_list = ['Aaniiih Nakoda College', 'Adams State University', 'Adelphi University', 'Alabama Agricultural & Mechanical University', 'Alabama State University', 'Alaska Christian College', 
                 'Alaska Pacific University', 'Albany State University', 'Albany Technical College', 'Alcorn State University', 'Allan Hancock College', 'Allen University', 'Altierus Career College', 
                 'Altierus Career College-Arlington', 'Altierus Career College-Bissonnet', 'Altierus Career College-Columbus', 'Altierus Career College-Fort Worth South', 'Altierus Career College-Norcross', 
                 'Alverno College', 'Alvin Community College', 'Amarillo College', 'American Academy of Art', 'American Baptist Theological Seminary', 'American Musical & Dramatic Academy', 'American River College', 
                 'American Samoa Community College', 'American University of Puerto Rico', 'Andrews University', 'Angelina College', 'Angelo State University', 'Antelope Valley College', 'Arizona State University', 
                 'Arizona Western College', 'Arkansas Baptist College', 'Arkansas State University Mid-South', 'Atenas College', 'Atlanta Metropolitan State College', 'Atlanta Technical College', 'Atlantic University College', 
                 'Augusta Technical College', 'Aurora University', 'Austin Community College', 'Azusa Pacific University', 'Azusa Pacific University College', 'Bacone College', 'Bainbridge State College', 'Bakersfield College', 
                 'Baptist Memorial College of Health Sciences', 'Barry University', 'Bastyr University', 'Baton Rouge Community College', 'Bay Mills Community College', 'Belhaven University', 'Bellevue College', 'Benedict College', 
                 'Benjamin Franklin Institute of Technology', 'Bennett College', 'Bergen Community College', 'Berkeley City College', 'Bethesda University', 'Bethune Cookman University', 'Beulah Heights University', 
                 'Big Bend Community College', 'Bishop State Community College', 'Blackfeet Community College', 'Bladen Community College', 'Bloomfield College', 'Blue Mountain Community College', 'Bluefield State College', 
                 'Boricua College', 'Bowie State University', 'Brazosport College', 'Brookhaven College', 'Broward College', 'Bunker Hill Community College', 'Butte College', 'Cabrillo College', 'California Baptist University', 
                 'California College San Diego', 'California College San Diego', 'California Lutheran University', 'California State Polytechnic University, Pomona', 'California State University - Sacramento', 
                 'California State University Channel Islands', 'California State University, Bakersfield', 'California State University, Chico', 'California State University, Dominguez Hills', 
                 'California State University, East Bay', 'California State University, Fresno', 'California State University, Fullerton', 'California State University, Long Beach', 'California State University, Los Angeles', 
                 'California State University, Monterey Bay', 'California State University, Northridge', 'California State University, San Bernardino', 'California State University, San Marcos', 'California State University, Stanislaus', 
                 'Calumet College of Saint Joseph', 'Cambridge College', 'Canada College', 'Cankdeska Cikana (Little Hoop) Community College', 'Capital Community College', 'Caribbean University', 'Caribbean University', 
                 'Caribbean University', 'Caribbean University', 'Carl Albert State College', 'Carlos Albizu University', 'Carlos Albizu University', 'Carolina College of Biblical Studies', 'Casa Loma College', 
                 'Cedar Valley College', 'Central Arizona College', 'Central Carolina Technical College', 'Central Georgia Technical College', 'Central New Mexico Community College', 'Central State University', 
                 'Century College', 'Cerritos Community College', 'Cerro Coso Community College', 'Chabot College', 'Chaffey Community College', 'Chaminade University of Honolulu', 
                 'Charlotte Christian College and Theological Seminary', 'Chattahoochee Valley Community College', 'Chemeketa Community College', 'Cheyney University of Pennsylvania', 'Chicago State University', 'Chief Dull Knife College', 
                 'Chowan University', 'Cisco College', 'Citrus Community College', 'City College', 'City College of New York - CUNY', 'City College of San Francisco', 'City College-Gainesville', 'City College-Miami', 'City Colleges of Chicago - Kennedy King College', 
                 'City Colleges of Chicago - Malcolm X College', 'City Colleges of Chicago Harry S Truman College', 'Claflin University', 'Clarendon College', 'Clark Atlanta University', 'Clayton State University', 'Clinton College', 'Clovis Community College', 
                 'Clovis Community College', 'Coahoma Community College', 'Coastal Bend College', 'Coastline Community College', 'Colegio Universitario de San Juan', 'Coleman University', 'College of Alameda', 'College of Du Page', 'College of Lake County', 'College of Menominee Nation', 
                 'College of Micronesia-FSM', 'College of Mount Saint Vincent', 'College of New Rochelle (The)', 'College of Saint Elizabeth', 'College of San Mateo', 'College of Southern Nevada', 'College of Staten Island/CUNY', 'College of the Canyons', 'College of the Desert', 
                 'College of the Mainland', 'College of the Muscogee Nation', 'College of the Sequoias', 'CollegeAmerica - Flagstaff', 'CollegeAmerica-Phoenix', 'Colorado State University-Pueblo', 'Columbia Basin College', 'Columbia Gorge Community College', 'Columbus Technical College', 
                 'Commonwealth of Puerto Rico Department of Education', 'Community Care College', 'Community College of Aurora', 'Community College of Denver', 'Community College of Philadelphia', 'Concordia College Alabama', 'Concordia University', 'Concordia University Texas', 
                 'Connors State College', 'Contra Costa College', 'Copper Mountain College', 'Coppin State University', 'Cossatot Community College of the University of Arkansas', 'Cosumnes River College', 'Cuesta College', 'Cumberland County College', 'CUNY Bernard M. Baruch College', 
                 'CUNY Borough of Manhattan Community College', 'CUNY Bronx Community College', 'CUNY Brooklyn College', 'CUNY Graduate School & University Center', 'CUNY Hunter College', 'CUNY John Jay College of Criminal Justice', 'CUNY LaGuardia Community College', 'CUNY Lehman College', 
                 'CUNY Medgar Evers College', 'CUNY Queens College', 'CUNY York College', 'CUNY, Hostos Community College', 'Cuyamaca College', 'Cypress College', 'Dallas Nursing Institute', 'Dalton State College', 'Del Mar College', 'Delaware State University', 'Delgado Community College', 
                 'Denmark Technical College', 'Dewey University', 'Dewey University', 'Dewey University', 'Dewey University', 'Dewey University', 'Dewey University', 'Diablo Valley College', 'Dillard University', 'Dine College', 'Dodge City Community College', 'Dominican College of Blauvelt', 
                 'Dominican University', 'Donnelly College', 'East Georgia State College', 'East Los Angeles College', 'East Mississippi Community College', 'East San Gabriel Valley ROP and Technical Center', 'East-West University', 'East-West University', 'Eastern New Mexico University', 
                 'Eastern New Mexico University', 'Eastern New Mexico University', 'Eastern New Mexico University', 'Eastern University', 'Eastfield College', 'Edgecombe Community College', 'Edmonds Community College', 'EDP University of Puerto Rico', 'EDP University of Puerto Rico Inc-San Sebastian', 
                 'Edward Waters College', 'El Camino College', 'El Centro College', 'El Paso Community College', 'Elizabeth City State University', 'Essex County College', 'Estrella Mountain Community College', 'Everest University-Brandon', 'Everest University-South Orlando', 
                 'Evergreen Valley College', 'Fairleigh Dickinson University', 'Faith Theological Seminary', 'Faulkner University', 'Fayetteville State University', 'Felician University', 'Fisk University', 'Florence - Darlington Technical College', 'Florida Agricultural & Mechanical University', 
                 'Florida Atlantic University', 'Florida International University', 'Florida Memorial University', 'Folsom Lake College', 'Fond du Lac Tribal & Community College', 'Fort Lewis College', 'Fort Peck Community College', 'Fort Valley State University', 'Frank Phillips College', 
                 'Fresno City College', 'Fresno Pacific University', 'Gadsden State Community College', 'Galveston College', 'Garden City Community College', 'GateWay Community College', 'Gateway Community College', 'Gavilan College', 'George Corley Wallace State Community College - Selma', 
                 'Georgia Gwinnett College', 'Georgia Military College', 'Georgia Piedmont Technical College', 'Georgia State University', 'Georgia State University-Perimeter College', 'Glendale Community College', 'Glendale Community College', 'Golden West College', 'Grace Mission University', 
                 'Grambling State University', 'Green River College', 'Grossmont College', 'Gupton-Jones College', 'H. Councill Trenholm State Community College', 'Halifax Community College', 'Hallmark University', 'Hampton University', 'Harold Washington College', 
                 'Harris - Stowe State University', 'Hartnell Community College', 'Haskell Indian Nations University', 'Hawaii Community College', 'Hawaii Pacific University', 'Heritage University', 'Herzing University-Atlanta', 'Herzing University-Birmingham', 'Herzing University-Kenner', 
                 'Herzing University-Minneapolis', 'Herzing University-Toledo', 'Herzing University-Winter Park', 'Highline College', 'Hillsborough Community College', 'Hinds Community College', 'Hodges University', 'Holmes Community College', 'Holy Names University', 
                 'Holyoke Community College', 'Homestead Schools', 'Honolulu Community College', 'Hope International University', 'Houston Baptist University', 'Houston Community College', 'Howard County Junior College District', 'Howard University', 'Hudson County Community College', 
                 'Humacao Community College', 'Humboldt State University', 'Humphreys University', 'Huston - Tillotson University', 'Ilisagvik College', 'Imperial Valley College', 'Institute of American Indian & Alaska Native Culture & ArtsDevelopment', 
                 'Instituto Tecnologico de Puerto Rico-Recinto de Manati', 'Inter American University of Puerto Rico - Aguadilla Campus', 'Inter American University of Puerto Rico - Arecibo Campus', 'Inter American University of Puerto Rico - Barranquitas Campus', 
                 'Inter American University of Puerto Rico - Bayamon Campus', 'Inter American University of Puerto Rico - Fajardo Campus', 'Inter American University of Puerto Rico - Guayama Campus', 'Inter American University of Puerto Rico - Metropolitan Campus', 
                 'Inter American University of Puerto Rico - Ponce Campus', 'Inter American University of Puerto Rico San German Campus', 'Irvine Valley College', 'J. F. Drake State Community and Technical College', 'Jackson State University', 'Jacksonville College', 
                 'Jarvis Christian College', 'John F. Kennedy University', 'Johnson & Wales University-Charlotte', 'Johnson C Smith University', 'Kapiolani Community College', 'Kauai Community College', 'Kean University', 'Keiser University', 'Kentucky State University', 
                 'Keweenaw Bay Ojibwa Community College', 'Kingsborough Commmunity College/CUNY', 'La Sierra University', 'Lac Courte Oreilles Ojibwa Community College', 'Lake Tahoe Community College', 'Lake Washington Institute of Technology', 'Lamar Community College', 
                 'Lamar State College - Port Arthur', 'Lane College', 'Laney College', 'Langston University', 'Laredo College', 'Las Positas College', 'Lawson State Community College', 'Lee College', 'Leech Lake Tribal College', 'Leeward Community College', 'LeMoyne - Owen College', 
                 'Life Pacific College', 'Limestone College', 'Lincoln College', 'Lincoln University', 'Lincoln University', 'Little Big Horn College', 'Little Priest Tribal College', 'LIU Riverhead', 'Livingstone College', 'Lone Star College System', 'Long Beach City College', 
                 'Long Island University', 'Los Angeles City College', 'Los Angeles Harbor College', 'Los Angeles Mission College', 'Los Angeles ORT College-Van Nuys Campus', 'Los Angeles Pierce College', 'Los Angeles Trade-Technical College', 'Los Angeles Valley College', 
                 'Los Medanos College', 'MacCormac College', 'Martin University', 'Marymount California University', 'McLennan Community College', 'McMurry University', 'Mendocino College', 'Mercy College', 'Meridian Community College', 'Merritt College', 'Mesa Community College', 
                 'Mesalands Community College', 'Metropolitan College of New York', 'Metropolitan State University', 'Metropolitan State University of Denver', 'Miami Dade College', 'Middlesex Community College', 'Miles College', 'Mills College', 'Mission College', 
                 'Mississippi Delta Community College', 'Mississippi Valley State University', 'Modesto Junior College', 'Montana State University - Northern', 'Montclair State University', 'Monterey Peninsula College', 'Montgomery College', 'Moorpark College', 
                 'Morehouse College', 'Moreno Valley College', 'Morgan Community College', 'Morgan State University', 'Morris College', 'Morton College', 'Mount Saint Mary University', 'Mount San Antonio College', 'Mountain View College', 'Mt. San Jacinto College', 
                 'Napa Valley College', 'National Louis University', 'National University', 'National University of Health Sciences (The)', 'Naugatuck Valley Community College', 'Navajo Technical University', 'Nebraska Indian Community College', 'Nevada State College', 
                 'New Jersey City University', 'New Mexico Highlands University', 'New Mexico Institute of Mining & Technology', 'New Mexico State University', 'New Mexico State University', 'New Mexico State University', 'New Mexico State University', 
                 'New Mexico State University', 'New Mexico State University', 'New York City College of Technology of the City University of New York', 'New York College of Health Professions', 'New York Institute of Technology', 'Norco College', 'Norfolk State University', 
                 'North Carolina Agricultural & Technical State University', 'North Carolina Central University', 'North Carolina Wesleyan College', 'North Hennepin Community College', 'North Lake College', 'Northeast Texas Community College', 'Northeastern Illinois University', 
                 'Northeastern Oklahoma A & M College', 'Northeastern State University', 'Northeastern Technical College', 'Northern Essex Community College', 'Northern Marianas College', 'Northern New Mexico College', 'Northern Oklahoma College', 'Northern Virginia Community College', 
                 'Northland Pioneer College', 'Northwest Indian College', 'Northwest Vista College', 'Norwalk Community College', 'Notre Dame de Namur University', 'Nova Southeastern University', 'Nueta Hidatsa Sahnish College', 'Nyack College', 'Oakton Community College', 
                 'Oakwood University', 'Oconee Fall Line Technical College', 'Odessa College', 'Oglala Lakota College', 'Oklahoma Panhandle State University', 'Oklahoma State University Institute of Technology - Okmulgee', 'Olive-Harvey College', 'Orange Coast College', 
                 'Orange County Community College', 'Orangeburg - Calhoun Technical College', 'Otis College of Art & Design', 'Our Lady of The Lake University', 'Oxnard College', 'Pacific Islands University', 'Pacific Rim Christian University', 'Pacific Union College', 
                 'Pacific University', 'Paine College', 'Palm Beach State College', 'Palo Alto College', 'Palo Alto University', 'Palomar College', 'Pamlico Community College', 'Pasadena City College', 'Passaic County Community College', 'Paul Quinn College', 'Peirce College', 
                 'Pennsylvania State University-Penn State Abington', 'Perry Technical Institute', 'Philander Smith College', 'Phoenix College', 'Pierce College', 'Pillar College', 'Pima County Community College', 'Pontifical Catholic University of Puerto Rico (The)', 
                 'Pontifical Catholic University of Puerto Rico (The)', 'Pontifical Catholic University of Puerto Rico (The)', 'Porterville College', 'Portland State University', 'Prairie State College', 'Prairie View Agricultural & Mechanical University', 
                 'Presbyterian Theological Seminary in America', 'Prince George s Community College', 'Pueblo Community College', 'Queensborough Community College-CUNY', 'Reading Area Community College', 'Redlands Community College', 'Reedley College', 
                 'Remington College', 'Remington College-Baton Rouge Campus', 'Remington College-Cleveland Campus', 'Remington College-Fort Worth Campus', 'Remington College-Heathrow Campus', 'Remington College-Honolulu Campus', 'Remington College-Houston Southeast Campus', 
                 'Remington College-Lafayette Campus', 'Remington College-Memphis Campus', 'Remington College-Mobile Campus', 'Remington College-North Houston Campus', 'Remington College-Shreveport Campus', 'Resurrection University', 'Richard J Daley College-City Colleges of Chicago', 
                 'Richland College', 'Rio Hondo Community College', 'Riverside City College', 'Robert Morris University Illinois', 'Robeson Community College', 'Rockland Community College', 'Rogers State University', 'Roosevelt University', 'Rust College', 
                 'Rutgers, the State University of New Jersey', 'Sacramento City College', 'Saddleback College', 'Saginaw Chippewa Tribal College', 'Saint Augustine College', 'Saint Augustine s University', 'Saint John s University', 'Saint Martin s University', 
                 'Saint Mary s College of California', 'Saint Paul College - A Community & Technical College', 'Saint Peter s University', 'Saint Philip s College', 'Saint Xavier University', 'Salish Kootenai College', 'Sampson Community College', 'San Antonio College', 
                 'San Bernardino Valley College', 'San Diego Christian College', 'San Diego City College', 'San Diego Mesa College', 'San Diego State University', 'San Francisco State University', 'San Jacinto Community College District', 'San Joaquin Delta College', 
                 'San Jose City College', 'San Jose State University', 'San Juan Bautista School of Medicine', 'San Juan College', 'Santa Ana College', 'Santa Barbara City College', 'Santa Fe Community College', 'Santa Monica College', 'Santa Rosa Junior College', 
                 'Santiago Canyon College', 'Savannah State University', 'Savannah Technical College', 'Schreiner University', 'Seattle Central College', 'Selma University', 'Seminole State College', 'Seminole State College of Florida', 'Seward County Community College', 
                 'Shaw University', 'Shelton State Community College', 'Shoreline Community College', 'Shorter College', 'Shorter University-College of Adult & Professional Programs', 'Sierra College', 'Simmons College of Kentucky', 'Sinte Gleska University', 
                 'Sisseton Wahpeton College', 'Sitting Bull College', 'Skyline College', 'Solano Community College', 'Sonoma State University', 'South Carolina State University', 'South Florida State College', 'South Georgia Technical College', 'South Louisiana Community College', 
                 'South Mountain Community College', 'South Plains College', 'South Suburban College of Cook County', 'South Texas College', 'Southeast Arkansas College', 'Southeastern Baptist College', 'Southeastern Oklahoma State University', 'Southern Crescent Technical College', 
                 'Southern University and Agricultural & Mechanical Colg at Baton Rouge', 'Southern University at New Orleans', 'Southern University at Shreveport - Bossier City', 'Southwest Mississippi Community College', 'Southwest Tennessee Community College', 
                 'Southwest Texas Junior College', 'Southwestern Adventist University', 'Southwestern Christian College', 'Southwestern Community College District', 'Southwestern Indian Polytechnic Institute', 'Spelman College', 'Springfield Technical Community College', 
                 'St. Catherine University', 'St. Edward s University', 'St. Mary s University', 'Stella and Charles Guttman Community College', 'Stevens-Henager College', 'Stillman College', 'Stone Child College', 'Sul Ross State University', 'SUNY College at Old Westbury', 
                 'SUNY Westchester Community College', 'Taft College', 'Talladega College', 'Tarrant County College District', 'TechMission', 'Temple College', 'Tennessee State University', 'Texas A&M International University', 'Texas A&M University - Corpus Christi', 
                 'Texas A&M University - Kingsville', 'Texas A&M University-San Antonio', 'Texas College', 'Texas Lutheran University', 'Texas Southern University', 'Texas Southmost College', 'Texas State Technical College', 'Texas State University', 'Texas Tech University', 
                 'Texas Wesleyan University', 'Texas Woman s University', 'Tohono O odham Community College', 
                 'Tougaloo College', 'Treasure Valley Community College', 'Trinidad State Junior College', 'Trinity College of Puerto Rico', 'Trinity International University-Florida', 'Trinity Washington University', 
                 'Triton College', 'Turtle Mountain Community College', 'Tuskegee University', 'Union County College', 'Union Institute & University', 'United Tribes Technical College', 
                 'Universal Technology College of Puerto Rico', 'Universidad Adventista De Las Antillas', 'Universidad Ana G. Mendez - Gurabo Campus', 'Universidad Ana G. Mendez, Carolina Campus', 
                 'Universidad Ana G. Mendez, Cupey Campus', 'Universidad Central de Bayamon', 'Universidad del Sagrado Corazón', 'Universidad Politecnica de Puerto Rico', 'Universidad Politecnica de Puerto Rico', 
                 'Universidad Politecnica de Puerto Rico', 'University of Alaska Fairbanks', 'University of Alaska Southeast', 'University of Arizona (The)', 'University of Arizona (The)', 'University of Arkansas at Pine Bluff', 
                 'University of Baltimore', 'University of California, Davis', 'University of California, Irvine', 'University of California, Merced', 'University of California, Riverside', 'University of California, Santa Barbara', 
                 'University of California, Santa Cruz', 'University of Central Florida', 'University of Connecticut-Hartford Campus', 'University of Fort Lauderdale', 'University of Guam', 'University of Hawaii - West Oahu', 
                 'University of Hawaii at Hilo', 'University of Hawaii at Manoa', 'University of Hawaii Maui College', 'University of Houston', 'University of Houston - Clear Lake', 'University of Houston - Downtown', 
                 'University of Houston - Victoria', 'University of Illinois at Chicago', 'University of La Verne', 'University of Maryland - Baltimore County', 'University of Maryland - Eastern Shore', 
                 'University of Massachusetts - Boston', 'University of Minnesota - Morris', 'University of Minnesota - Twin Cities', 'University of Nevada - Las Vegas', 'University of New Mexico', 'University of New Mexico', 
                 'University of New Mexico', 'University of New Mexico', 'University of North Carolina at Pembroke', 'University of North Texas at Dallas', 'University of Puerto Rico - Arecibo', 
                 'University of Puerto Rico - Cayey University College', 'University of Puerto Rico - Humacao University College', 'University of Puerto Rico - Mayaguez', 'University of Puerto Rico - Medical Science Campus', 
                 'University of Puerto Rico - Rio Piedras Campus', 'University of Puerto Rico, Aguadilla Regional College', 'University of Saint Thomas', 'University of San Francisco', 'University of Texas - Rio Grande Valley', 
                 'University of Texas at Arlington', 'University of Texas at El Paso', 'University of Texas at San Antonio', 'University of Texas Health Science Center at San Antonio', 'University of Texas of the Permian Basin', 
                 'University of the District of Columbia', 'University of the Incarnate Word', 'University of the Pacific', 'University of the Southwest', 'University of the Virgin Islands', 'University of Washington - Seattle', 
                 'University of Washington-Tacoma Campus', 'University of West Alabama', 'Valencia College', 'Vanguard University of Southern California', 'Vaughn College of Aeronautics and Technology', 'Ventura College', 
                 'Vernon College', 'Victor Valley Community College', 'Victoria College', 'Virginia State University', 'Virginia Union University', 'Virginia University of Lynchburg', 'Voorhees College', 'Warner Pacific University', 'Washington Adventist University', 'Waubonsee Community College', 'Wayne County Community College District', 'Wenatchee Valley College', 'West Hills College Lemoore', 'West Hills Community College', 'West Los Angeles College', 'West Virginia State University', 'Western Dakota Technical Institute', 'Western Nevada College', 'Western New Mexico University', 'Western Texas College', 'Wharton County Junior College', 'White Earth Tribal and Community College', 'Whittier College', 'Wilberforce University', 'Wilbur Wright College', 'Wiley College', 'William Paterson University of New Jersey', 'Williamsburg Technical College', 'Windward Community College', 'Winston-Salem State University', 'Woodbury University', 'Woodland Community College', 'Xavier University of Louisiana', 'Yakima Valley College', 'Yuba College']

def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3

# Perform exact match intersection
print(f'Exact Match: {intersection(a_list, b_list)}')

# Perform fuzzy string matching
tuples_list = [max([(fuzz.token_set_ratio(i,j),j) for j in b_list]) for i in a_list]
print(f'Fuzzy Match {tuples_list}')